# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jᥱffr᧐.𝓲𝓸

subtitle: 'Never waste a crisis. | All in web3.'
favicon: /asserts/rss.png
avatar: /asserts/IMG_9850.JPG
description: ''
keywords:
author: Jᥱffr᧐
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://jeffro.io
permalink: posts/:url/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

inject:
  head:
    - <link href="https://cdn.jsdelivr.net/gh/duyplus/fontawesome-pro@6.1.1/css/all.min.css" rel="stylesheet" type="text/css">
    - <link href="https://cdn.staticaly.com/gh/hung1001/font-awesome-pro-v6/44659d9/css/all.min.css" rel="stylesheet" type="text/css" />
    # - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    # - <link rel="stylesheet" href="https://kit.fontawesome.com/676d8a3bda.css" crossorigin="anonymous">
    # - <script src="https://kit.fontawesome.com/676d8a3bda.js" crossorigin="anonymous"></script>
    # - <link href="https://fonts.font.im/css?family=Arbutus+Slab" rel="stylesheet">
    # - <link href="https://fonts.font.im/css?family=Lora" rel="stylesheet">
    # - <link rel="preconnect" href="https://fonts.googleapis.com">
    # - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    # - <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lxgw-wenkai-screen-webfont/1.6.0/style.css" integrity="sha512-OyzdGE7U3mczF3FgVnnaxE9n3B+Sz4KUwLsiw/70FgUkT2GhD3pxOhfYUJd6dCQN3U5sNVsQieBrtSXTH6V1mA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   
    - <script async src="https://www.googletagmanager.com/gtag/js?id=G-X7WWYNGW5F"></script>
    - <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-X7WWYNGW5F'); </script>